### ISSUE TITLE
Powershell file encoding issue

### ISSUE THREAD

**Issue by LostLogic** [Maelstromage/Log4jSherlock#15]
Small issue - It seems Windows has issues detecting that the script is encoded in UTF8, and rather than defaulting to UTF8, defaults to ANSI.
Recommend encoding the file as UTF8 BOM which alleviates the issue.

The variable $global:color is set in the $code block, but called in the display-logo function which has no knowledge of the color.
Recommend moving the variable to main or just defining -foreground magenta in display-logo.

Thanks for all the work you've put into the script! Had something similar coded myself, but not as extensive. Helped me detect some sources that was previously hidden. Cheers!

**Comment by Maelstromage** [comment]
Thank you for this, I have reencoded it
