### ISSUE TITLE
Set-StrictMode and undefined variables

### ISSUE THREAD

**Issue by Guyver1wales** [Maelstromage/Log4jSherlock#17]
you need to define all variables etc as people who use Set-StrictMode -Latest will get failures.

InvalidOperation: C:\Users\kim.akers\github\PowerShell\log4j-scanner\Log4Sherlock.ps1:196
Line |
196 | }while($continue -ne $false)
| ~~~~~~~~~
| The variable '$continue' cannot be retrieved because it has not been set.

**Comment by Maelstromage** [comment]
Thank you, this should be good now.
