### ISSUE TITLE
CTRL+C to QuitCTRL+C to QuitCTRL+C to QuitCTRL+C

### ISSUE THREAD

**Issue by sammer003** [Maelstromage/Log4jSherlock#18]
single W10 computer in WG with the local computer name in computers.txt, RunAs local administrator in ISE

Output is a table, then one continuous line of CTRL+C to QuitCTRL+C to QuitCTRL+C to QuitCTRL+C that doesn't end, see snip:
![image](https://user-images.githubusercontent.com/10051290/146799610-ffeea9e0-b63f-41f6-a4c6-096b3ad43e79.png)

This was .ps1 code downloaded directly from Github at 9:15am (MST) - this code displayed the LOG4jSherlock in pink at the start.
No log files were created in C:\Log4jSherlock or c:\temp (where it was saved and run from).

Others on Reddit are experiencing the same issue: https://www.reddit.com/r/sysadmin/comments/rkaco9/comment/hp9xk39/?utm_source=share&utm_medium=web2x&context=3

**Comment by Guyver1wales** [comment]
can confirm, when run from Server 2016 to scan all domain servers in my lab, it fails to scan the domain servers, only scan the local server and then fails with:
    {
        "Error":  null
    }

All I get are the CTRL+C to quit messages.

**Comment by upcboy** [comment]
Issue [19](https://github.com/Maelstromage/Log4jSherlock/issues/19) has a fix for this

**Comment by sammer003** [comment]
> Issue [19](https://github.com/Maelstromage/Log4jSherlock/issues/19) has a fix for this

I added your line to 192 and got the same issue:
![image](https://user-images.githubusercontent.com/10051290/146814769-2fea5d57-6a31-48a2-9f06-65127c2a9695.png)

**Comment by A-BigHead** [comment]
> > Issue [19](https://github.com/Maelstromage/Log4jSherlock/issues/19) has a fix for this
> 
> I added your line to 192 and got the same issue: ![image](https://user-images.githubusercontent.com/10051290/146814769-2fea5d57-6a31-48a2-9f06-65127c2a9695.png)

Adding the fix to line 192 makes the script end correctly.

To resolve the other problem, I just commented out line 190 with a # like:

`#write-host “CTRL+C to Quit” -NoNewLine`

it’s not needed, and makes all the logs clean up…

**Comment by Maelstromage** [comment]
Thank you all,
I removed the CTRL+C to Quit now that it quits automatically.

**Comment by upcboy** [comment]
> Thank you all, I removed the CTRL+C to Quit now that it quits automatically.

@Maelstromage  it looks like now it does not write logs for the last computer or if there is only 1 machine in the list. it exists before writing the logs.

**Comment by Maelstromage** [comment]
Thank you upcboy, I have resolved the issue where it will not write the logs for a single computer, and the same goes for the last computer in the list. This should be good now.
