### ISSUE TITLE
Script does not know when to stop

### ISSUE THREAD

**Issue by AndreasTheDead** [Maelstromage/Log4jSherlock#19]
Hey,
First that’s a great resource to quickly scan devices. But i noticed that the Script will not stop running after it completed all Jobs.

To archive that I added 
`if ((get-job) -eq $Null){
  $continue = $false
}`
To the While Do loop in Line 192. then the Script  would exit after the jobs where finished.
Is that really needed or did I overlook something?

**Comment by upcboy** [comment]
I did something very similar and it works great!

**Comment by sammer003** [comment]
> I did something very similar and it works great!

I just tried this and it didn't work. Perhaps I put the code in the wrong place?
![image](https://user-images.githubusercontent.com/10051290/146815101-09cefa09-efec-442f-9e10-7025b5a3e8b9.png)

https://github.com/Maelstromage/Log4jSherlock/issues/19#issuecomment-998154603

**Comment by upcboy** [comment]
> > I did something very similar and it works great!
> 
> I just tried this and it didn't work. Perhaps I put the code in the wrong place? 



I edited the whole if statement to slow down the output a bit for me.
```powershell
if ((get-date -Format 'fff') -eq '500'){
  $loopJobs =Get-Job -State Running
  $loopJobs
  write-host "CTRL+C to Quit" -NoNewline
  if ($null -eq $loopJobs){
    $continue=$false
  }   
}
```

**Comment by Maelstromage** [comment]
I have rewriten the code, it should not stop when all jobs are finished.
