### ISSUE TITLE
Stop scanning empty DVD/CD drives

### ISSUE THREAD

**Issue by Guyver1wales** [Maelstromage/Log4jSherlock#22]
Please consider altering your Drive variable to stop picking up empty optical drives by using:

$drives = (Get-WmiObject -Class Win32_LogicalDisk -Filter "DriveType ='3'").DeviceID

**Comment by Guyver1wales** [comment]
function Scan-System{
        param($filetypes)
        $scannedfiles =@()
        $DriveErrors = @()
        **$Drives = (Get-WmiObject -Class Win32_LogicalDisk -Filter "DriveType ='3'").DeviceID**
        #$drives = @('c:\test','g:\test\')
        foreach ($Drive in $Drives) {
            $searchingmessage = "Searching Drive $drive on host $env:ComputerName..."
            write-host $searchingmessage -ForegroundColor Cyan
            $global:vulnerabilityresults += $searchingmessage
            $javaFiles = Get-ChildItem **"$Drive\\"** -Recurse -ErrorVariable DriveError -include $filetypes -ErrorAction SilentlyContinue #| out-null
            foreach ($javaFile in $javaFiles){
                $scannedfiles += [pscustomobject](Scan-File $javaFile)
            }
        }
        $global:csv = $Scannedfiles
        $global:Errors += @{Error=$DriveError.exception.message}
        $scannedfiles += $global:Errors
        $scannedfiles = convertto-json $scannedfiles
        return $scannedfiles
    }

**Comment by Emusp** [comment]
Also, I think it would be great to limit the number of disk to scan. 
eg. you don't won't to scan a 100TB disk, it will take forever. 

Will look into something like: scan all disk, but max xxx GB in size.

**Comment by Guyver1wales** [comment]
better to make that user optional rather than taking the choice away

**Comment by Maelstromage** [comment]
> Please consider altering your Drive variable to stop picking up empty optical drives by using:
> 
> $drives = (Get-WmiObject -Class Win32_LogicalDisk -Filter "DriveType ='3'").DeviceID

Thank you so much, I have added this.
