### ISSUE TITLE
WinRM service start if not already started

### ISSUE THREAD

**Issue by VF1JVeritech** [Maelstromage/Log4jSherlock#27]
Some domains have the WinRM service set to manual.  This script does not check or start the service.  I added the following for a quick scan of domain computers in the function Scan-MultipleSystems right after line 169.

Get-Service -Name WinRM -ComputerName $comp | Set-Service -Status Running

I'm sure this can be fixed up to check and start if not running.  I tested on a system with it not running and on a system with it running and no errors reported and both scans completed.

**Comment by Maelstromage** [comment]
Added line, Thank you.
