### ISSUE TITLE
Log4jSherlok is returning vulnerable

### ISSUE THREAD

**Issue by SKAatGIT** [Maelstromage/Log4jSherlock#29]
Hello,

first of all - Thank you soo much for the script !

I still get a positive result even if the Log4Jcore or log is on version 2.17.1.
May this is the issue here because the script falls back to default on line 27 I guess ?

if($version -eq 'version=2.17.0'){$CVE = $null; $CVSSScore = $null; $FixedVersion = $true}

Thank you,

SKA

**Comment by Maelstromage** [comment]
you are right, thank you so much. I will fix this.

**Comment by Maelstromage** [comment]
This is fixed now, thank you.
